package Animals;

public class RandomNames {

    public RandomNames(){
    }

    public String genderSelectNames(String chooseGenderName) {
        if (chooseGenderName.equalsIgnoreCase("female")) {
            return (femaleNames());
        } else
            return (maleNames());
    }

    private String femaleNames() {

        String[] randomFemaleNames = new String[]{

                "Annalise",
                "Audrina",
                "Quinn",
                "Emmalee",
                "Cindy",
                "Jessie",
                "Leilani",
                "Matilda",
                "Gisselle",
                "Delilah",
                "Violet",
                "Serenity",
                "Allison",
                "Jada",
                "Kamari",
                "Summer",
                "Micaela",
                "Isabel",
                "Maia",
                "Sandra",
                "Alexus",
                "Patricia",
                "Kelly",
                "Mira",
                "Keira",
                "Emerson",
                "Katie",
                "Hadassah",
                "Larissa",
                "Chana",
                "Jayden",
                "Jacqueline",
                "Ava",
                "Skylar",
                "Kailey",
                "Itzel",
                "Holly",
                "Lizeth",
                "Kristina",
                "Brielle",
                "Kate",
                "Miracle",
                "Jazlyn",
                "Annika",
                "Evangeline",
                "Kendra",
                "Kaylen",
                "Elle",
                "Deborah",
                "Viviana",
                "Leyla",
                "Dana",
                "Susan",
                "Camille",
                "Mary",
                "Charity",
                "Evie",
                "Gia",
                "Sloane",
                "Shania",
                "Annabel",
                "Hope",
                "Lilly",
                "Ashanti",
                "Alicia",
                "Phoenix",
                "Crystal",
                "Judith",
                "Miranda",
                "Nevaeh",
                "Brenna",
                "Yasmine",
                "Hillary",
                "Dayanara",
                "Kyra",
                "Jaylynn",
                "India",
                "Aaliyah",
                "Magdalena",
                "Erin",
                "Saniya",
                "Imani",
                "Cassie",
                "Hadley",
                "Karissa",
                "Virginia",
                "Sasha",
                "Maggie",
                "Belen",
                "Hazel",
                "Alina",
                "Angelina",
                "Cristina",
                "Sariah",
                "Jenna",
                "Gina",
                "Kimora",
                "Eileen",
                "Kaiya",
                "Daphne"};

        return randomFemaleNames[(int) ((Math.random() * 101) + 1)-1];
    }

    private String maleNames() {

        String[] randomMaleNames = new String[]{
                "Yadiel",
                "Aedan",
                "Leo",
                "Colin",
                "Leandro",
                "Caiden",
                "Brayan",
                "Evan",
                "Vincent",
                "Mathias",
                "Erick",
                "Dashawn",
                "Xzavier",
                "Hugo",
                "Kyan",
                "Braedon",
                "Porter",
                "Daniel",
                "Cannon",
                "Beckham",
                "Willie",
                "Bo",
                "Ty",
                "Aldo",
                "Spencer",
                "Kristian",
                "Kole",
                "Derrick",
                "Damarion",
                "Rigoberto",
                "Carlos",
                "Nathaniel",
                "Jace",
                "Gael",
                "Deon",
                "Jeramiah",
                "Tanner",
                "Gordon",
                "Jamari",
                "Noah",
                "Levi",
                "Alfred",
                "Thomas",
                "Zavier",
                "Lyric",
                "Jayson",
                "Casey",
                "Jovan",
                "Douglas",
                "Clay",
                "Amir",
                "Kelton",
                "Allan",
                "Ernest",
                "Dante",
                "Terry",
                "Jordyn",
                "Cale",
                "Darryl",
                "Tyree",
                "Mekhi",
                "Prince",
                "Ahmad",
                "Seamus",
                "Emery",
                "Gunnar",
                "Owen",
                "Leonel",
                "Ashton",
                "Jasper",
                "Mohammed",
                "Bobby",
                "Aydan",
                "Kameron",
                "Brice",
                "Kolton",
                "Leonard",
                "Finn",
                "Maurice",
                "Caden",
                "Damion",
                "Ralph",
                "Kevin",
                "Kaeden",
                "Rogelio",
                "Nathanael",
                "Jaime",
                "James",
                "Marcelo",
                "Hunter",
                "Paul",
                "Braxton",
                "Tony",
                "Angelo",
                "Madden",
                "Samson",
                "Brodie",
                "Nicholas",
                "Damian",
                "Brendan"};

        return randomMaleNames[(int) ((Math.random() * 101) + 1)-1];
    }
}

